services:
  - type: web
    name: gamelinkbo
    env: python
    buildCommand: ""
    startCommand: python init.py && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
    plan: free
